blueprint:
  name: Smart AC Control
  description: Auto AC control using external sensor. Created by Fahad.
  domain: automation
  input:
    climate_device:
      name: AC
      selector:
        entity:
          domain: climate
    temperature_sensor:
      name: Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
    target_temperature:
      name: Target
      selector:
        number:
          min: 16
          max: 30
          unit_of_measurement: °C
          step: 0.5
    margin:
      name: Margin
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1
          unit_of_measurement: °C
    cooldown_time:
      name: Cooldown
      selector:
        number:
          min: 60
          max: 3600
          step: 30
          unit_of_measurement: s

trigger:
  - platform: state
    entity_id: !input temperature_sensor

variables:
  current_temp: "{{ states[inputs.temperature_sensor] | float }}"
  target_temp: "{{ inputs.target_temperature | float }}"
  margin: "{{ inputs.margin | float }}"
  cooldown: "{{ inputs.cooldown_time | int }}"
  ac: !input climate_device
  ac_state: "{{ state_attr(ac, 'hvac_action') }}"
  last_changed: "{{ as_timestamp(now()) - as_timestamp(state_attr(this.entity_id, 'last_triggered') or 0) }}"

condition:
  - condition: template
    value_template: "{{ last_changed > cooldown }}"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ current_temp > (target_temp + margin) }}"
        sequence:
          - service: climate.turn_on
            target:
              entity_id: !input climate_device
          - service: climate.set_temperature
            data:
              temperature: !input target_temperature
              hvac_mode: cool
            target:
              entity_id: !input climate_device
      - conditions:
          - condition: template
            value_template: "{{ current_temp < (target_temp - margin) }}"
        sequence:
          - service: climate.turn_off
            target:
              entity_id: !input climate_device

mode: restart
max_exceeded: silent
