blueprint:
  name: Smart AC Control
  description: Auto AC control using external sensor. Created by Fahad.
  domain: automation
  input:
    climate_device:
      name: AC
      selector:
        entity:
          domain: climate
    temperature_sensor:
      name: Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
    target_temperature:
      name: Target
      selector:
        number:
          min: 16
          max: 30
          unit_of_measurement: "°C"
    margin:
      name: Margin
      selector:
        number:
          min: 0.5
          max: 5.0
          step: 0.1
          unit_of_measurement: "°C"
    cooldown_time:
      name: Cooldown
      selector:
        number:
          min: 30
          max: 3600
          unit_of_measurement: "s"

trigger:
  - platform: state
    entity_id: !input temperature_sensor

variables:
  current_temp_
