blueprint:
  name: External Sensor AC Control
  description: Smart AC with external sensor
  domain: automation
  author: xfahad

  input:
    climate_device:
      name: Climate
      selector:
        entity:
          domain: climate
    temperature_sensor:
      name: Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
    target_temperature:
      name: Target
      selector:
        number:
          min: 16
          max: 30
          step: 0.5
          unit_of_measurement: °C
    margin:
      name: Margin
      default: 1.0
      selector:
        number:
          min: 0.5
          max: 3.0
          step: 0.1
    cooldown_time:
      name: Cooldown (sec)
      default: 120
      selector:
        number:
          min: 30
          max: 600
          step: 10

mode: single

variables:
  current_temp: "{{ states(inputs.temperature_sensor) | float }}"
  target_temp: "{{ inputs.target_temperature | float }}"
  margin: "{{ inputs.margin | float }}"
  ac_state: "{{ state_attr(inputs.climate_device, 'hvac_action') }}"
  cooldown: "{{ inputs.cooldown_time | int }}"
  last_changed: >
    {{ (as_timestamp(now()) - as_timestamp(state_attr(this.entity_id, 'last_triggered') or 0)) | int }}

trigger:
  - platform: state
    entity_id: !input temperature_sensor

condition:
  - condition: template
    value_template: "{{ last_changed > cooldown }}"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ current_temp > (target_temp + margin) }}"
        sequence:
          - service: climate.turn_on
            target:
              entity_id: !input climate_device
          - service: climate.set_temperature
            data:
              entity_id: !input climate_device
              temperature: "{{ target_temp }}"
      - conditions:
          - condition: template
            value_template: "{{ current_temp < (target_temp - margin) }}"
        sequence:
          - service: climate.turn_off
            target:
              entity_id: !input climate_device
