blueprint:
  name: Smart Climate Control Based on Time and Temperature
  description: >
    A smart automation blueprint to manage AC operation based on temperature and time.
    - Sets a sleep temperature at 5:00 PM.
    - Intervenes during night time only if temperature exceeds a critical limit.
    - Operates during daytime hours with temperature thresholds.
    - If temperature drops too low during daytime, it switches AC to 'auto' mode to pause cooling.
    
    Created by Fahad (@fahad) — Naqsh Holding
  domain: automation
  input:
    climate_entity:
      name: Climate Device
      selector:
        entity:
          domain: climate

    temperature_sensor:
      name: Temperature Sensor
      selector:
        entity:
          domain: sensor

    sleep_temperature:
      name: Sleep Temperature
      default: 25
      selector:
        number:
          min: 18
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

    critical_temp:
      name: Critical Temperature (Night)
      default: 28
      selector:
        number:
          min: 25
          max: 35
          step: 0.5
          unit_of_measurement: "°C"

    daytime_cool_temp:
      name: Cooling Threshold (Daytime)
      default: 22
      selector:
        number:
          min: 18
          max: 26
          step: 0.5
          unit_of_measurement: "°C"

    lower_limit_temp:
      name: Minimum Temperature Before Cooling Pause (Daytime)
      default: 21
      selector:
        number:
          min: 18
          max: 25
          step: 0.5
          unit_of_measurement: "°C"

mode: single

trigger:
  - platform: time
    at: "17:00:00"
    id: time_trigger

  - platform: numeric_state
    entity_id: !input temperature_sensor
    above: !input critical_temp
    for:
      minutes: 10
    id: critical_high_temp

  - platform: numeric_state
    entity_id: !input temperature_sensor
    above: !input daytime_cool_temp
    for:
      minutes: 10
    id: high_day_temp

  - platform: numeric_state
    entity_id: !input temperature_sensor
    below: !input lower_limit_temp
    for:
      minutes: 10
    id: low_day_temp

condition: []

action:
  - choose:
      # 1. Sleep Mode Activation at 5:00 PM
      - conditions:
          - condition: trigger
            id: time_trigger
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input climate_entity
            data:
              hvac_mode: cool
          - service: climate.set_temperature
            target:
              entity_id: !input climate_entity
            data:
              temperature: !input sleep_temperature

      # 2. Nighttime Emergency Cooling if temperature exceeds critical_temp
      - conditions:
          - condition: time
            after: "17:00:00"
            before: "06:00:00"
          - condition: trigger
            id: critical_high_temp
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input climate_entity
            data:
              hvac_mode: cool
          - service: climate.set_temperature
            target:
              entity_id: !input climate_entity
            data:
              temperature: !input sleep_temperature

      # 3. Daytime Cooling if temperature exceeds threshold
      - conditions:
          - condition: time
            after: "06:00:00"
            before: "17:00:00"
          - condition: trigger
            id: high_day_temp
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input climate_entity
            data:
              hvac_mode: cool
          - service: climate.set_temperature
            target:
              entity_id: !input climate_entity
            data:
              temperature: !input daytime_cool_temp

      # 4. Daytime Cooling Pause if temperature drops too low
      - conditions:
          - condition: time
            after: "06:00:00"
            before: "17:00:00"
          - condition: trigger
            id: low_day_temp
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input climate_entity
            data:
              hvac_mode: auto
